🎁 Adding indices to Bulkrax Tables (#813)
* 🎁 Adding indices to Bulkrax Tables

Note: this is a best guess of what could use indexing.  The guess is
based on my recent querying.

- `add_index :bulkrax_entries, :identifier` :: because the identifier is
  an important concept for an import.
- `add_index :bulkrax_entries, :type` :: because filtering on the type
  of an entry is important.
- `add_index :bulkrax_entries, [:importerexporter_id,
  :importerexporter_type], name: 'bulkrax_entries_importerexporter_idx` :: this is a foreign key for the entries
  relationship to the importer/exporter.

- `add_index :bulkrax_pending_relationships, :parent_id` :: a foreign key
- `add_index :bulkrax_pending_relationships, :child_id`  :: a foreign key

- `add_index :bulkrax_statuses, [:statusable_id, :statusable_type],
  name: 'bulkrax_statuses_statusable_idx'` :: a foreign key
- `add_index :bulkrax_statuses, [:runnable_id, :runnable_type], name:
  'bulkrax_statuses_runnable_idx'` :: a foreign key
- `add_index :bulkrax_statuses, :error_class` :: when querying what's in
  error, this index is helpful; also one used for grouping.

* ⚙️ Pinning to more specific version of dry-monads

In downstream implementations, I'm seeing 1.4.0.  I'm seeing 1.5.0
failing in specs.

* ⚙️ Removing yaml aliases from test database config

In specs, I was seeing the following error:

```
Psych::AliasesNotEnabled: Cannot load database configuration: Alias
parsing was not enabled. To enable it, pass `aliases: true` to
`Psych::load` or `Psych::safe_load`.
```

Given that we rarely touch the file, I see no benefit to using an alias
relative to the above error exception.

* ⚙️ Tightening Redis Dependency for Tests

Looking at Adventist, which has a working Redis instance, I see that it
uses 4.2.5; however the newer version (v5) has the following error:

`ArgumentError: wrong number of arguments (given 1, expected 0)`; that
error is part of redis-client which is part of redis 5.0.6

* 🤖 Removing the 2.6 tests

First, this is well past end of life.  And second, I'm seeing the
following in the 2.6 build:

```
ArgumentError: wrong number of arguments (given 4, expected 1)
/home/runner/work/bulkrax/bulkrax/vendor/bundle/ruby/2.6.0/gems/psych-5.1.0/lib/psych.rb:322:in
`safe_load'
```

Not interested in fighting against that.

* 🤖 Favoring redis_config from downstream application

As this is for specs, I'm favoring that functionality/implementation.

* 🤖 Pinning dev version of Psych

I'm seeing the following in CI:

```
ArgumentError: wrong number of arguments (given 4, expected 1)
/home/runner/work/bulkrax/bulkrax/vendor/bundle/ruby/2.7.0/gems/psych-5.1.0/lib/psych.rb:322:in
`safe_load'
```

* comment out coverage step due to pipeline failure

* comment out coverage step due to pipeline failure

* bump coverage report version in attempts to resolve pipeline

---------

Co-authored-by: Shana Moore <shana@scientist.com>